"# conor-s-tut" 


Errors

pandas_6.py
    
    # from creds import cdict
    # ImportError: cannot import name 'cdict' At line 9


pandas_3.py
    At line 16:
    # pl.drop(["last 10  games results","Match Status","Unnamed: 0"],
        axis = 1, inplace = True)
    # ValueError: labels ['last 10  games results' 'Match Status'] not contained in axis

phue_test.py
  #May be related to line 10: b = Bridge('192.168.2.74')#

 #File "C:\Users\<username>\AppData\Local\Continuum\Anaconda3\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  #timeout: timed out

   